server:
  port: 8091

spring:
  application:
    name: notification-worker
  kafka:
    # broker-a -> consumes the REAL account.created produced by account-service
    bootstrap-servers: broker-a:9092
    consumer:
      group-id: notification

account-service:
  url: http://localhost:8091
