server:
  port: 8093

spring:
  application:
    name: notification-worker
  kafka:
    bootstrap-servers: broker-b:9092
    consumer:
      group-id: notification

account-service:
  url: http://localhost:8091
